original data
1. EDA with statisical tests and plots
2. preprocessing (standard scaler, remove duplicates, one hot, label encoding, round all stupid values, feature selection?)
3. train test split
4. lazy predict
5. hyperparam tuning
6. xai

syntetic data
1. determine rows with high similiarity on whole data set and remove
2. retrain and test with same config but augmented with syntetic
3. apply cross-val, nested cross-val maybe more?
4. compare results

final
1. add new features like bmi and ibw
2. test
3. compare

# Setup

In [4]:
!pip install ydata-profiling
!pip install lazypredict
!pip install catboost
!pip install ipywidgets
!pip install lazypredict==0.2.16
!pip install scikit-learn==1.4.2

Collecting ydata-profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 29.7 MB/s eta 0:00:00
Collecting wordcloud>=1.9.3
  Downloading wordcloud-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.1/511.1 kB 60.4 MB/s eta 0:00:00
Collecting imagehash==4.3.1
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 37.6 MB/s eta 0:00:00
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (3.6.3)
Collecting htmlmin==0.1.12
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy<2.2,>=1.16.0 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (1.25.2)
Requirement already satisfied: tqdm<5,>=4.48.2 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (1.9.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: requests<3,>=2.24.0 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (2.32.3)
Collecting dacite>=1.8
  Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (3.1.5)
Collecting visions[type_image_path]<0.8.2,>=0.7.5
  Downloading visions-0.8.1-py3-none-any.whl (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 21.0 MB/s eta 0:00:00
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (6.0.2)
Collecting typeguard<5,>=3
  Downloading typeguard-4.4.2-py3-none-any.whl (35 kB)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /root/venv/lib/python3.10/site-packages (from ydata-profiling) (2.1.4)
Collecting numba<=0.61,>=0.56.0
  Downloading numba-0.61.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 81.2 MB/s eta 0:00:00
Collecting pydantic>=2
  Downloading pydantic-2.11.4-py3-none-any.whl (443 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.9/443.9 kB 61.4 MB/s eta 0:00:00
Collecting multimethod<2,>=1.4
  Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Collecting statsmodels<1,>=0.13.2
  Downloading statsmodels-0.14.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 94.1 MB/s eta 0:00:00
Collecting phik<0.13,>=0.11.1
  Downloading phik-0.12.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (686 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.1/686.1 kB 101.5 MB/s eta 0:00:00
Collecting PyWavelets
  Downloading pywavelets-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 91.5 MB/s eta 0:00:00
Requirement already satisfied: pillow in /root/venv/lib/python3.10/site-packages (from imagehash==4.3.1->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /root/venv/lib/python3.10/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: pyparsing>=2.2.1 in /root/venv/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /root/venv/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /root/venv/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /root/venv/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: cycler>=0.10 in /root/venv/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/venv/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.56.0)
Requirement already satisfied: packaging>=20.0 in /root/venv/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Collecting llvmlite<0.45,>=0.44.0dev0
  Downloading llvmlite-0.44.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 54.4 MB/s eta 0:00:00
Requirement already satisfied: tzdata>=2022.1 in /root/venv/lib/python3.10/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.1)
Requirement already satisfied: pytz>=2020.1 in /root/venv/lib/python3.10/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.1)
Requirement already satisfied: joblib>=0.14.1 in /root/venv/lib/python3.10/site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Collecting typing-inspection>=0.4.0
  Downloading typing_inspection-0.4.0-py3-none-any.whl (14 kB)
Collecting pydantic-core==2.33.2
  Downloading pydantic_core-2.33.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 124.4 MB/s eta 0:00:00
Collecting annotated-types>=0.6.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: typing-extensions>=4.12.2 in /root/venv/lib/python3.10/site-packages (from pydantic>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/venv/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.1.31)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/venv/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/venv/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.3.0)
Requirement already satisfied: idna<4,>=2.5 in /root/venv/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Collecting patsy>=0.5.6
  Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.9/232.9 kB 42.5 MB/s eta 0:00:00
WARNING: visions 0.8.1 does not provide the extra 'type_image_path'
Collecting puremagic
  Downloading puremagic-1.29-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 13.2 MB/s eta 0:00:00
Collecting networkx>=2.4
  Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 110.2 MB/s eta 0:00:00
Requirement already satisfied: attrs>=19.3.0 in /root/venv/lib/python3.10/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.1.0)
Requirement already satisfied: six>=1.5 in /root/venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27080 sha256=bc5cd36b303841f7777df82dfa70ea3426c79db346a90bf8ff4f87582fe5a2e2
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin
Installing collected packages: puremagic, htmlmin, typing-inspection, typeguard, PyWavelets, pydantic-core, patsy, networkx, multimethod, llvmlite, dacite, annotated-types, pydantic, numba, imagehash, wordcloud, visions, statsmodels, phik, ydata-profiling
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.21
    Uninstalling pydantic-1.10.21:
      Successfully uninstalled pydantic-1.10.21
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy 3.4.4 requires pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.11.4 which is incompatible.
Successfully installed PyWavelets-1.8.0 annotated-types-0.7.0 dacite-1.9.2 htmlmin-0.1.12 imagehash-4.3.1 llvmlite-0.44.0 multimethod-1.12 networkx-3.4.2 numba-0.61.0 patsy-1.0.1 phik-0.12.4 puremagic-1.29 pydantic-2.11.4 pydantic-core-2.33.2 statsmodels-0.14.4 typeguard-4.4.2 typing-inspection-0.4.0 visions-0.8.1 wordcloud-1.9.4 ydata-profiling-4.16.1

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Collecting lazypredict
  Downloading lazypredict-0.2.16-py2.py3-none-any.whl (14 kB)
Collecting xgboost
  Downloading xgboost-3.0.0-py3-none-manylinux_2_28_x86_64.whl (253.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.9/253.9 MB 2.7 MB/s eta 0:00:00
Requirement already satisfied: joblib in /root/venv/lib/python3.10/site-packages (from lazypredict) (1.4.2)
Collecting mlflow>=2.0.0
  Downloading mlflow-2.22.0-py3-none-any.whl (29.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.0/29.0 MB 66.4 MB/s eta 0:00:00
Requirement already satisfied: click in /root/venv/lib/python3.10/site-packages (from lazypredict) (8.1.8)
Requirement already satisfied: tqdm in /root/venv/lib/python3.10/site-packages (from lazypredict) (4.67.1)
Requirement already satisfied: pandas in /root/venv/lib/python3.10/site-packages (from lazypredict) (2.1.4)
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 98.1 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn in /root/venv/lib/python3.10/site-packages (from lazypredict) (1.1.3)
Collecting pytest-runner
  Downloading pytest_runner-6.0.1-py3-none-any.whl (7.2 kB)
Collecting gunicorn<24
  Downloading gunicorn-23.0.0-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 12.9 MB/s eta 0:00:00
Requirement already satisfied: matplotlib<4 in /root/venv/lib/python3.10/site-packages (from mlflow>=2.0.0->lazypredict) (3.6.3)
Requirement already satisfied: Jinja2<4,>=2.11 in /root/venv/lib/python3.10/site-packages (from mlflow>=2.0.0->lazypredict) (3.1.5)
Requirement already satisfied: markdown<4,>=3.3 in /root/venv/lib/python3.10/site-packages (from mlflow>=2.0.0->lazypredict) (3.7)
Collecting docker<8,>=4.0.0
  Downloading docker-7.1.0-py3-none-any.whl (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 35.5 MB/s eta 0:00:00
Collecting graphene<4
  Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 17.8 MB/s eta 0:00:00
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /toolkit-cache/0.2.14/python3.10/kernel-libs/lib/python3.10/site-packages (from mlflow>=2.0.0->lazypredict) (1.4.42)
Requirement already satisfied: numpy<3 in /root/venv/lib/python3.10/site-packages (from mlflow>=2.0.0->lazypredict) (1.25.2)
Requirement already satisfied: pyarrow<20,>=4.0.0 in /toolkit-cache/0.2.14/python3.10/kernel-libs/lib/python3.10/site-packages (from mlflow>=2.0.0->lazypredict) (17.0.0)
Requirement already satisfied: scipy<2 in /root/venv/lib/python3.10/site-packages (from mlflow>=2.0.0->lazypredict) (1.9.3)
Collecting Flask<4
  Downloading flask-3.1.0-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.0/103.0 kB 32.0 MB/s eta 0:00:00
Collecting mlflow-skinny==2.22.0
  Downloading mlflow_skinny-2.22.0-py3-none-any.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 123.3 MB/s eta 0:00:00
Requirement already satisfied: alembic!=1.10.0,<2 in /toolkit-cache/0.2.14/python3.10/kernel-libs/lib/python3.10/site-packages (from mlflow>=2.0.0->lazypredict) (1.13.2)
Collecting importlib_metadata!=4.7.0,<9,>=3.7.0
  Downloading importlib_metadata-8.7.0-py3-none-any.whl (27 kB)
Collecting gitpython<4,>=3.1.9
  Downloading GitPython-3.1.44-py3-none-any.whl (207 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.6/207.6 kB 46.1 MB/s eta 0:00:00
Collecting databricks-sdk<1,>=0.20.0
  Downloading databricks_sdk-0.52.0-py3-none-any.whl (700 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 700.2/700.2 kB 99.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /root/venv/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (4.12.2)
Requirement already satisfied: protobuf<7,>=3.12.0 in /root/venv/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (4.25.6)
Requirement already satisfied: cloudpickle<4 in /root/venv/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (2.2.1)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /toolkit-cache/0.2.14/python3.10/kernel-libs/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (0.5.0)
Requirement already satisfied: pyyaml<7,>=5.1 in /root/venv/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in /root/venv/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (2.32.3)
Requirement already satisfied: cachetools<6,>=5.0.0 in /root/venv/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (5.5.1)
Collecting fastapi<1
  Downloading fastapi-0.115.12-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 24.5 MB/s eta 0:00:00
Collecting uvicorn<1
  Downloading uvicorn-0.34.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 21.6 MB/s eta 0:00:00
Collecting opentelemetry-api<3,>=1.9.0
  Downloading opentelemetry_api-1.32.1-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.3/65.3 kB 17.8 MB/s eta 0:00:00
Collecting opentelemetry-sdk<3,>=1.9.0
  Downloading opentelemetry_sdk-1.32.1-py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.0/119.0 kB 27.2 MB/s eta 0:00:00
Requirement already satisfied: packaging<25 in /root/venv/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (24.2)
Requirement already satisfied: pydantic<3,>=1.10.8 in /root/venv/lib/python3.10/site-packages (from mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (2.11.4)
Requirement already satisfied: pytz>=2020.1 in /root/venv/lib/python3.10/site-packages (from pandas->lazypredict) (2025.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/venv/lib/python3.10/site-packages (from pandas->lazypredict) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.1 in /root/venv/lib/python3.10/site-packages (from pandas->lazypredict) (2025.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /root/venv/lib/python3.10/site-packages (from scikit-learn->lazypredict) (3.5.0)
Collecting nvidia-nccl-cu12
  Downloading nvidia_nccl_cu12-2.26.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (318.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.1/318.1 MB 1.9 MB/s eta 0:00:00
Requirement already satisfied: Mako in /toolkit-cache/0.2.14/python3.10/kernel-libs/lib/python3.10/site-packages (from alembic!=1.10.0,<2->mlflow>=2.0.0->lazypredict) (1.3.5)
Requirement already satisfied: urllib3>=1.26.0 in /root/venv/lib/python3.10/site-packages (from docker<8,>=4.0.0->mlflow>=2.0.0->lazypredict) (2.3.0)
Requirement already satisfied: Werkzeug>=3.1 in /root/venv/lib/python3.10/site-packages (from Flask<4->mlflow>=2.0.0->lazypredict) (3.1.3)
Collecting itsdangerous>=2.2
  Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Collecting blinker>=1.9
  Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Collecting graphql-relay<3.3,>=3.1
  Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Collecting graphql-core<3.3,>=3.1
  Downloading graphql_core-3.2.6-py3-none-any.whl (203 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.4/203.4 kB 31.0 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in /root/venv/lib/python3.10/site-packages (from Jinja2<4,>=2.11->mlflow>=2.0.0->lazypredict) (3.0.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /root/venv/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (1.4.8)
Requirement already satisfied: pyparsing>=2.2.1 in /root/venv/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (3.2.1)
Requirement already satisfied: pillow>=6.2.0 in /root/venv/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (11.1.0)
Requirement already satisfied: cycler>=0.10 in /root/venv/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/venv/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (4.56.0)
Requirement already satisfied: contourpy>=1.0.1 in /root/venv/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (1.3.1)
Requirement already satisfied: six>=1.5 in /root/venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->lazypredict) (1.17.0)
Requirement already satisfied: greenlet!=0.4.17 in /toolkit-cache/0.2.14/python3.10/kernel-libs/lib/python3.10/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.0.0->lazypredict) (3.0.3)
Requirement already satisfied: google-auth~=2.0 in /root/venv/lib/python3.10/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (2.38.0)
Collecting starlette<0.47.0,>=0.40.0
  Downloading starlette-0.46.2-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 12.7 MB/s eta 0:00:00
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 14.1 MB/s eta 0:00:00
Collecting zipp>=3.20
  Downloading zipp-3.21.0-py3-none-any.whl (9.6 kB)
Collecting importlib_metadata!=4.7.0,<9,>=3.7.0
  Downloading importlib_metadata-8.6.1-py3-none-any.whl (26 kB)
Collecting deprecated>=1.2.6
  Downloading Deprecated-1.2.18-py2.py3-none-any.whl (10.0 kB)
Collecting opentelemetry-semantic-conventions==0.53b1
  Downloading opentelemetry_semantic_conventions-0.53b1-py3-none-any.whl (188 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 kB 17.6 MB/s eta 0:00:00
Requirement already satisfied: pydantic-core==2.33.2 in /root/venv/lib/python3.10/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (2.33.2)
Requirement already satisfied: annotated-types>=0.6.0 in /root/venv/lib/python3.10/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /root/venv/lib/python3.10/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (0.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /root/venv/lib/python3.10/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (2025.1.31)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/venv/lib/python3.10/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /root/venv/lib/python3.10/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (3.10)
Collecting h11>=0.8
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Requirement already satisfied: wrapt<2,>=1.10 in /root/venv/lib/python3.10/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.22.0->mlflow>=2.0.0->lazypredict) (1.14.1)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.2-py3-none-any.whl (24 kB)

In [11]:
!pip install shap

Collecting shap
  Downloading shap-0.47.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (992 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 992.3/992.3 kB 47.9 MB/s eta 0:00:00
Requirement already satisfied: pandas in /root/venv/lib/python3.10/site-packages (from shap) (2.1.4)
Requirement already satisfied: scikit-learn in /root/venv/lib/python3.10/site-packages (from shap) (1.4.2)
Requirement already satisfied: packaging>20.9 in /root/venv/lib/python3.10/site-packages (from shap) (24.2)
Requirement already satisfied: numpy in /root/venv/lib/python3.10/site-packages (from shap) (1.25.2)
Requirement already satisfied: numba>=0.54 in /root/venv/lib/python3.10/site-packages (from shap) (0.61.0)
Requirement already satisfied: cloudpickle in /root/venv/lib/python3.10/site-packages (from shap) (2.2.1)
Requirement already satisfied: typing-extensions in /root/venv/lib/python3.10/site-packages (from shap) (4.12.2)
Requirement already satisfied: tqdm>=4.27.0 in /root/venv/lib/python3.10/site-packages (from shap) (4.67.1)
Requirement already satisfied: scipy in /root/venv/lib/python3.10/site-packages (from shap) (1.9.3)
Collecting slicer==0.0.8
  Downloading slicer-0.0.8-py3-none-any.whl (15 kB)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /root/venv/lib/python3.10/site-packages (from numba>=0.54->shap) (0.44.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/venv/lib/python3.10/site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /root/venv/lib/python3.10/site-packages (from pandas->shap) (2025.1)
Requirement already satisfied: tzdata>=2022.1 in /root/venv/lib/python3.10/site-packages (from pandas->shap) (2025.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /root/venv/lib/python3.10/site-packages (from scikit-learn->shap) (3.5.0)
Requirement already satisfied: joblib>=1.2.0 in /root/venv/lib/python3.10/site-packages (from scikit-learn->shap) (1.4.2)
Requirement already satisfied: six>=1.5 in /root/venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)
Installing collected packages: slicer, shap
Successfully installed shap-0.47.2 slicer-0.0.8

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

In [14]:
import pandas as pd
from ydata_profiling import ProfileReport
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.base import BaseEstimator, TransformerMixin

import lazypredict
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.svm import SVC
from sklearn.ensemble import StackingClassifier

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform

import shap

In [17]:
real_data = pd.read_csv('/work/real-data.csv')

# EDA

## First Look

In [20]:
real_data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [23]:
real_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [30]:
real_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [26]:
profile = ProfileReport(real_data, title="Profiling Report - Real data")

In [27]:
profile

Summarize dataset:   0%|          | 0/22 [00:00<?, ?it/s, Describe variable: Weight]
Summarize dataset:  55%|█████▍    | 12/22 [00:00<00:00, 84.91it/s, Describe variable: MTRANS]
100%|██████████| 17/17 [00:00<00:00, 99.93it/s]
Summarize dataset: 100%|██████████| 90/90 [00:13<00:00,  6.49it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:06<00:00,  6.26s/it]
Render HTML: 100%|██████████| 1/1 [00:02<00:00,  2.54s/it]

In [36]:
# Remove duplicate rows from real_data_new
real_data_new = real_data.drop_duplicates().reset_index(drop=True)

In [45]:
# Manually specify the desired order of the NObeyesdad categories
ordered_categories = ['Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III']

# Plotting with manually specified category order
plt.figure(figsize=(12, 8))
sns.boxplot(x='NObeyesdad', y='Weight', data=real_data_new, order=ordered_categories, color='lightgrey')
plt.title('Weight vs NObeyesdad Categories')
plt.ylabel('Weight (kg)')
plt.xticks(rotation=45)
plt.show()

# Preprocessing

# remove duplicate
# one hot/true false: gender, family_history_with_overweight, favc, smoke, scc, mtrans
# to int: age, fcvc, ncp, ch20, faf, tue
# standard scaler: age, height, weight,
# label encoding: caec, calc

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a441f35e-4b4c-4c50-b56a-1aea6b800ed8' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>